### ISSUE TITLE
Newton-Raphson algorithm failed to converge.

### ISSUE THREAD

**Issue by xiaosefengyun** [RayDeCampo/nodejs-xirr#2]
I have a set of data like this
[{ amount: 2839.2, when: 2018-01-21T16:00:00.000Z },
  { amount: 207.7, when: 2018-01-24T16:00:00.000Z },
  { amount: -2526, when: 2018-04-26T16:00:00.000Z } ]
It can be calculated in Excel, but an exception was reported with node-xirr "Newton-Raphson algorithm failed to converge." I read the source code because newton (presentValue, guess, options) returned false here. Can you help look at what caused it?

**Comment by RayDeCampo** [comment]
The usual way to look at these types of problems is that a positive amount represents monies received (withdrawals) and a negative amount represents monies invested (deposits).

In your example you are receiving money on Jan 21 and Jan 24 and not depositing money until Apr 26.  That kind of cash flow does not represent an investment where money is put to work over a period of time.  Because of this the rubric used in nodejs-xirr to calculate a decent guess at the starting value for the Newton-Raphson algorithm fails to pick a starting point that converges.

In this case, the simplest thing to do would be to change your data by changing the signs:

        var transactions = [];
        transactions.push({ amount: -2839.2, when: new Date('2018-01-21T16:00:00.000Z') });
        transactions.push({ amount: -207.7, when: new Date('2018-01-24T16:00:00.000Z') });
        transactions.push({ amount: 2526, when: new Date('2018-04-26T16:00:00.000Z') });

        var result = xirr(transactions);
        assert.equal(-0.514174, result.toPrecision(6));

Now the library comes up with a good guess and the algorithm converges.  Now the data represents investing $2839.20 on Jan 21, then $207.70 on Jan 24 and receiving $2526 on Apr 26 for an annual rate of return of -51.4%.

**Comment by xiaosefengyun** [comment]
Thank you. I changed the signs to solve this problem.

**Comment by Renukushwah1101** [comment]
org.decampo.xirr.OverflowException: Candidate overflow: {guess=0.1, iteration=188, candidate=-Infinity, value=-1.536442899055107E11, derivative=-8.345988024991577E-298}
	at org.decampo.xirr.NewtonRaphson$Calculation.setCandidate(NewtonRaphson.java:166)
	at org.decampo.xirr.NewtonRaphson$Calculation.solve(NewtonRaphson.java:213)
	at org.decampo.xirr.NewtonRaphson.inverse(NewtonRaphson.java:89)
	at org.decampo.xirr.NewtonRaphson.findRoot(NewtonRaphson.java:70)
	at org.decampo.xirr.NewtonRaphson$Builder.findRoot(NewtonRaphson.java:136)
	at org.decampo.xirr.Xirr.xirr(Xirr.java:155)
	at org.decampo.xirr.Xirr$Builder.xirr(Xirr.java:262)

how can i fix this error.
